global using Xunit;
global using Ancient.Ecs;
global using FluentAssertions;
global using Ancient.Ecs.Test.TestSubjects.Components;
global using Ancient.Ecs.Test.TestSubjects.Systems;
global using Ancient.Ecs.Test.TestSubjects.Events;
global using Ancient.Ecs.Configurations;
global using AutoFixture.Xunit2;
global using Moq;